# usage: "<font-name> <font-size> <italic?> <bold?>"  example: "Arial 14 italic bold
font = "Arial 12"

# default rooms (set to the specified amount on startup) !lowercase!
default = {"bathroom": 1,
           "bedroom": 1,
           "kitchen": 1,
           "living room": 1}

# rooms and their needed furniture per room
rooms = {
    "Bathroom": {"Bath/Shower": 1,
                 "Bathroom Sink": 1,
                 "Toilet": 1,
                 "Bathroom Accessory": 3,
                 "Trash bin": 1,
                 "Cabinet": 1,
                 "Ceiling Lights": 1,
                 "Light Switch": 1,
                 "Rug": 1},
    "Bedroom": {"Bed": 1,
                "Wardrobe": 1,
                "Drawer": 2,
                "Bedroom Seat": 1,
                "Radiator": 1,
                "Decoration": 1,
                "Ceiling Lights": 1,
                "Light Switch": 1,
                "Rug": 1},
    "Children's room": {"Children's Bed": 1,
                        "Wardrobe": 1,
                        "Toy": 3,
                        "Radiator": 1,
                        "Ceiling Lights": 1,
                        "Light Switch": 1,
                        "Rug": 1},
    "Dining room": {"Chair": 3,
                    "Table": 1,
                    "Radiator": 1,
                    "Ceiling Lights": 1,
                    "Light Switch": 1,
                    "Rug": 1,
                    "Decoration": 2},
    "Dressing room": {"Wardrobe": 1,
                      "Decoration": 2,
                      "Mirror": 1,
                      "Radiator": 1,
                      "Ceiling Lights": 1,
                      "Light Switch": 1,
                      "Rug": 1},
    "Game room": {"Gaming Chair": 1,
                  "Gaming Table": 1,
                  "PC": 1,
                  "Monitor": 1,
                  "Keyboard & Mouse": 1,
                  "Radiator": 1,
                  "Ceiling Lights": 1,
                  "Light Switch": 1,
                  "Rug": 1,
                  "Decoration": 3},
    "Guestroom": {"Bed": 1,
                  "Wardrobe": 1,
                  "Decoration": 2,
                  "Radiator": 1,
                  "Ceiling Lights": 1,
                  "Light Switch": 1,
                  "Rug": 1},
    "Gym": {"Home Gym": 5,
            "Ceiling Lights": 1,
            "Light Switch": 1},
    "Hallway": {"Desk": 1,
                "Cabinet": 1,
                "Radiator": 1,
                "Ceiling Lights": 1,
                "Light Switch": 1,
                "Rug": 1},
    "Kitchen": {"Kitchen Cabinet": 3,
                "Kitchen Sink": 1,
                "Kitchen Accessory": 4,
                "Ceiling Lights": 1,
                "Light Switch": 1,
                "Rug": 1},
    "Laundry room": {"Washing Machine": 1,
                     "Bathroom Accessory": 1,
                     "Ceiling Lights": 1,
                     "Light Switch": 1,
                     "Rug": 1},
    "Library": {"Bookshelf": 4,
                "Seat": 1,
                "Ceiling Lights": 1,
                "Light Switch": 1,
                "Rug": 1,
                "Decoration": 2},
    "Living room": {"Sofa": 2,
                    "Cabinet": 3,
                    "Table": 2,
                    "Radiator": 1,
                    "Decoration": 2,
                    "Ceiling Lights": 1,
                    "Light Switch": 1},
    "Music room": {"Instrument": 3,
                   "Notes": 3,
                   "Decoration": 3,
                   "Ceiling Lights": 1,
                   "Light Switch": 1,
                   "Rug": 1},
    "Office": {"Study Table": 1,
               "Office Chair": 1,
               "Cabinet": 1,
               "PC": 1,
               "Monitor": 1,
               "Decoration": 2,
               "Radiator": 1,
               "Ceiling Lights": 1,
               "Light Switch": 1,
               "Rug": 1},
    "Pet room": {"Decoration": 3,
                 "Toy": 3,
                 "Radiator": 1,
                 "Ceiling Lights": 1,
                 "Light Switch": 1,
                 "Rug": 1},
    "Storage room": {"Misc": 4,
                     "Cabinet": 3,
                     "Ceiling Lights": 1,
                     "Light Switch": 1,
                     "Rug": 1,
                     "Decoration": 3},
    "TV room": {"Sofa": 2,
                "TV": 1,
                "Coffee Table": 1,
                "Entertainment Center": 1,
                "Radiator": 1,
                "Ceiling Lights": 1,
                "Light Switch": 1,
                "Rug": 1}
    }